### ISSUE TITLE
fixest page questions

### ISSUE THREAD

**Issue by NickCH-K** [stata2r/stata2r.github.io#19]
Hoping we can get this out before too long -

1. Should I go ahead and add `feglm`, `iplot`, `wald`, and did? Might have some time next week.
2. How did I not know about `a/b` interaction terms until now??? That would have been handy
3. I notice we have `summary()` for SE adjustment on the fly. Do we want `etable()` here? We haven't introduced it by that point in the page, but seems like it's what people would want most of the time.

Seems like if someone (possibly me) can take a crack at #1, and we can decide whether we're switching formats, there might be more minor fixes later but that would be enough to go live.

**Comment by kylebutts** [comment]
1. I think that would be great! I don't know how to do `did` with the sample data, so we should label that section with "this doesn't run", or we can use https://github.com/kylebutts/did2s/blob/main/data/df_hom.rda from {did2s}
2. Yeah, I love `i()` :-)
3. I think both is a good idea. I can add that today

I am going to work on searching for commands this weekend I think (though I am working at a ski resort, so I may get distracted by the views :-)
