### ISSUE TITLE
Low-package framing

### ISSUE THREAD

**Issue by NickCH-K** [stata2r/stata2r.github.io#2]
One of the petrifying things about R for Stata users is the endless list of packages you need before you even get started. However, **fixest** and **data.table** are pretty darn flexible and you can get a lot done with just those two. 

As such, one useful framing for `index.html` might be that we are taking you from "Stata in two packages to R in two packages" - those two packages being **reghdfe** and **estout** on the Stata side (and **gtools** for a third if you're feeling spicy) to **fixest** and **data.table**. Yes, R will need investment in other packages for certain tasks and models, moreso than Stata, but with these two under your belt you can get pretty far (and at the risk of bloat there's the potential for a third page that does map out a limited set of common Stata tasks to other non-**fixest**/**data.table** packages).

My week is weird so I probably won't be dedicating much time to this (or figuring out how to work the HTML generation code) until next week.

**Comment by kylebutts** [comment]
![image](https://user-images.githubusercontent.com/19961439/143086797-e534b565-bcf4-40a2-8347-b0c4ab6123c1.png)
I think that's somewhat how I'm framing it on the front page? Obviously just a draft of the language, but I think it comes off as really friendly with the emojis

**Comment by grantmcdermott** [comment]
@NickCH-K I dig the addition of:

> Plus, they are flexible (👌✨) and can help you avoid R's 'package overload.' Depending on what you do in Stata, you might even be able to cut back, going from three packages - reghdfe, estout and gtools - to just two.

on the landing page.

Can we close?
