### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by grantmcdermott** [stata2r/stata2r.github.io#20]
Right now, the search functionality is pretty limited (unless I'm doing something wrong). If we search for, say, "IV" it just suggests the **fixest** main page instead of taking me down to the relevant section. Can we fine-tune this a bit, @kylebutts?

**Comment by grantmcdermott** [comment]
Any resolution/progress on this, @kylebutts?

**Comment by kylebutts** [comment]
Yeah, I answered the [algolia people](https://docsearch.algolia.com/apply/) and they were supposed to send me an API key, but I didn't get it. Thanks for the reminder, following up now..

**Comment by kylebutts** [comment]
Completed by #39
