### ISSUE TITLE
Error on R side in leads and lags

### ISSUE THREAD

**Issue by simon-lowe** [stata2r/stata2r.github.io#27]
Hi,

Thanks a lot for this (even though I'm an R user)! I think there is an error in the leads and lag sections for R, you inverted the leads and lags.

Thanks,
Simon

**Comment by simon-lowe** [comment]
Second tiny thing (and I'm not sure whether this is a version problem, though I think I have the latest version of data.table):
dat[, index_within_carrier := .I, by = carrier] 
For me this does not create an index by group.

Thanks again,
Simon

**Comment by grantmcdermott** [comment]
Both are errors and should be corrected now. Thanks for flagging @simon-lowe!

**Comment by simon-lowe** [comment]
Thanks a lot for all your amazing work!
