### ISSUE TITLE
Use Map instead of lapply?

### ISSUE THREAD

**Issue by grantmcdermott** [stata2r/stata2r.github.io#28]
This one has been nagging at me for a while. As useful as `lapply()` is, it suffers from a lack of direct equivalents in other languages. So, it just adds a layer of inscrutability to the commands that we show here.

A pretty simple alternative would be to use [`base::Map()`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/funprog.html), which essentially does exactly the same thing (and more) and could serve as a drop-in replacement. Almost every other language has some version of map, and I think the name is much more intuitive even if you haven't encountered it before. The only difference is a reversal of argument order, i.e. we _map functions over elements_, whereas we _loop elements on functions_. 

As an example,

```r
dat[, lapply(.SD, mean), .SDcols=is.numeric]
```
would become

```r
dat[, Map(mean, .SD), .SDcols=is.numeric] 
```

More context provided by [this Twitter poll](https://twitter.com/grant_mcdermott/status/1488276560582877184). I've also reached out to a few Stata users and asked them which they prefer. All of them said that Map was more intuitive and I think that should be the end goal of this site.

Thoughts @kylebutts @NickCH-K?

**Comment by NickCH-K** [comment]
I've never actually used it myself, and the name is better, but I do really dislike the argument order reversal, since so many functions, outside of regressions, do data-first for arguments, especially anything written more recently.

How strong is the lapply standard in data.table docs? I'd favor matching that, too.

**Comment by kylebutts** [comment]
> All of them said that Map was more intuitive and I think that should be the end goal of this site.

I think this is true partially. I also think there’s a group of tidyverse R users that want to use data.table for speed/mem reasons who have found it useful. They probably use {purrr} though, so Map may be intuitive to them or may cause them confusion b/c data and function are switched relative to purrr::map

> How strong is the lapply standard in data.table docs? I'd favor matching that, too.

This is a good point I think, though I have a hard time looking through data.table docs even as an experienced R user

**Comment by grantmcdermott** [comment]
Thanks both. 

I don't want to push my own hobby horse too hard. But I think we should recognise that `purrr::map` is the odd one out w.r.t. argument ordering. `map()` in [Julia](https://docs.julialang.org/en/v1/base/collections/#Base.map), [Python](https://python-reference.readthedocs.io/en/latest/docs/functions/map.html), etc. etc. all take the function -> elements approach. (I understand why the tidy team chose the name and ordering they did, but it's always bothered me a bit.) At any rate, my main concern is making these comparisons as intuitive as possible for the modal reader. I'm not so concerned about matching the DT docs exactly, for instance, since I don't think most people will dive into those. Maybe a different poll 😈

**Comment by grantmcdermott** [comment]
Closing in light of https://github.com/Rdatatable/data.table/issues/5336
