### ISSUE TITLE
marginaleffects::plot_cap in iplot section after this Issue is resolved

### ISSUE THREAD

**Issue by grantmcdermott** [stata2r/stata2r.github.io#29]

**Comment by grantmcdermott** [comment]
@NickCH-K do you want to add / close this issue? Looks to me that the latest **modelsummary** release (just on CRAN) includes the necessary support for the CIs. This should close our original TO-DO list 🎉.

**Comment by grantmcdermott** [comment]
(I can do to. Just need to know the equivalent Stata command that you had in mind...)

**Comment by NickCH-K** [comment]
Awesome! Added.
