### ISSUE TITLE
About feols weights option

### ISSUE THREAD

**Issue by GuantingYi** [stata2r/stata2r.github.io#30]
Hey,

Thanks for setting up this amazing website, it really helped me grabbing the essence of how to use R in my analysis. But I am wondering if feols has the option to weight observations like stata does? aweight, pweight, etc. I searched for it online but I haven't found any answers yet. Thanks!!

**Comment by kylebutts** [comment]
Hi there,

The option is called `weights`. You can look up function parameters by typing `?feols` and it will pull up documentation. It's the same thing as -help command- in State.

**Comment by GuantingYi** [comment]
Thanks for your reply! I actually saw the documentation, but it seems like it doesn't distinguish different weighting methods like Stata does, maybe I missed something here.

**Comment by kylebutts** [comment]
The `weights` option is equivalent to `pweight`. You should only ever use `pweight` in regressions anyways.

**Comment by grantmcdermott** [comment]
@kylebutts I think you've got a typo above. The `weights` argument in R is like Stata's `aweight` (i.e. analytic weights). 

(At least, this is the most common case when using the formula interface. The `weights` argument in R can be used pretty flexibly, but 99% of the time you want to stick with something like the below. An exception is if you're doing survey-based regressions but then you want the dedicated **survey** package rather than **fixest**.)

```stata
. sysuse auto
(1978 Automobile Data)

. reg mpg weight [aweight = length]
(sum of wgt is   1.3907e+04)

...

------------------------------------------------------------------------------
         mpg |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
      weight |  -.0058966   .0004975   -11.85   0.000    -.0068884   -.0049049
       _cons |   39.07051   1.591745    24.55   0.000     35.89742    42.24359
------------------------------------------------------------------------------
```

```r
auto = haven::read_dta("http://www.stata-press.com/data/r16/auto.dta")
fixest::feols(mpg ~ weight, auto, weights = ~length)
#> OLS estimation, Dep. Var.: mpg
#> Observations: 74 
#> Standard-errors: IID 
#>              Estimate Std. Error  t value  Pr(>|t|)    
#> (Intercept) 39.070507   1.591745  24.5457 < 2.2e-16 ***
#> weight      -0.005897   0.000498 -11.8523 < 2.2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> RMSE: 44.6   Adj. R2: 0.656432

```
