### ISSUE TITLE
Fill in Time Series/Panel Data: Code typos

### ISSUE THREAD

**Issue by lrberge** [stata2r/stata2r.github.io#32]
Hi everyone!

I've been perusing the `data.table` section (it's quite exhaustive, that's a gold mine!) and I've stumbled onto what I think is a coding typo in the section: [Fill in Time Series/Panel Data](https://stata2r.github.io/data.table/#fill-in-time-series-panel-data).

Instead of:
```r
dat = CJ(id = 1:3, yr = _2001:2004_)[, x := runif(12)]

# etc...

dat[, c("xlag", "xlead") := NULL][
    yr %in% c(1,3), _y_ := NA]
```

It should be:

```r
dat = CJ(id = 1:3, yr = _1:4_)[, x := runif(12)]

# etc...

dat[, c("xlag", "xlead") := NULL][
    yr %in% c(1,3), _x_ := NA]
```

Thanks again for writing this!

**Comment by kylebutts** [comment]
Fixed, thanks!
