### ISSUE TITLE
Add an example showing weights for fixest?

### ISSUE THREAD

**Issue by taylorjwright** [stata2r/stata2r.github.io#35]
Great job on this! 

I think something that people might want to know about for fixest is how to add weights. I don't mind writing up the example, if you'd like.

**Comment by kylebutts** [comment]
Yes, that would be awesome if you could! For the most part, we use the same dataset throughout the examples, so use that if you could 🙏🏼

**Comment by taylorjwright** [comment]
Great, will do!

**Comment by kylebutts** [comment]
Completed in #35
