### ISSUE TITLE
Issue with variable definition 

### ISSUE THREAD

**Issue by AbdulrasheedIsah** [stata2r/stata2r.github.io#37]
<img width="595" alt="Screenshot 2023-02-05 at 11 15 48" src="https://user-images.githubusercontent.com/83364078/216813479-0ed830ba-8c55-4c88-bdd0-bbc205bd6337.png">

You created the variable as y but later referred to it as x, leading to error. It would be helpful to fix this. Thanks

**Comment by grantmcdermott** [comment]
Good spot, thanks. Should be fixed now.
