### ISSUE TITLE
Preferring in-place manipulation

### ISSUE THREAD

**Issue by NickCH-K** [stata2r/stata2r.github.io#4]
I noticed in the `data.table` page that it includes both `d[order(x)]` and `setorder(d, x)`. I wonder if, in the interest of simplicity since this is only a primer, we should prefer only one way of doing things. In particular it probably makes sense to prefer in-place manipulation using `set` functions over the alternative, since this is generally the faster approach.

This means `setorder` over `i=order`, not attempting to fill in the ??s for an alternative to `setnames`, `setDT` over `as.data.table`, and `setcolorder` over doing the same task using `j`. Also generally using `:=` when possible.

Does this sound good as a standard?

Follow-up: should _non_-in-place manipulation reassign the data set so as to actually be equivalent to the Stata operation? i.e. `keep in 1/200` isn't actually equivalent to `d[1:200]`, it's equivalent to `d = d[1:200]`. This seems like a pretty clearly good idea to me.

**Comment by kylebutts** [comment]
I think both of your points are the correct idea. I originally was thinking to do it both ways to make piping easier to understand, but I sort of forgot you can pipe into setDT, setnames, etc. :-)

**Comment by grantmcdermott** [comment]
Closing this based on https://github.com/stata2r/stata2r.github.io/commit/19122f427f9e39a16d21fe5a61a16b31e26a2419 but we can reopen if you still aren't happy.
