### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by grantmcdermott** [stata2r/stata2r.github.io#43]
@kylebutts I'm encountering a [build error](https://github.com/stata2r/stata2r.github.io/actions/runs/7715130185/job/21028946238) after a recent minor update in f94fd065bf6619bda61779514c3fc7a1bc36ec7b. Did i do something wrong here?

**Comment by kylebutts** [comment]
Nope the log looks like we need an update to astro. Can do in a few hours

**Comment by grantmcdermott** [comment]
Great, thanks. Feel free to close this when you do.
