### ISSUE TITLE
Broken link to `fastverse` website

### ISSUE THREAD

**Issue by arcruz0** [stata2r/stata2r.github.io#44]
Hi and thanks for the great resource!

The link to the `fastverse` website is broken here:

https://github.com/stata2r/stata2r.github.io/blob/1679a74090064d9185468c25a77d215518271553/src/content/docs/extras.mdx?plain=1#L550

The new link should be <https://fastverse.github.io/fastverse/>

Thanks!

**Comment by grantmcdermott** [comment]
Thanks!
